import { defineCollection } from '@nocobase/database';
export default defineCollection({
  sortable: true,
  logging: true, name: 'crmLeads', title: 'Leads',
  fields: [
    { type: 'string', name: 'name', interface: 'input', uiSchema: { type: 'string', title: 'Lead Name', 'x-component': 'Input' } },
    { type: 'string', name: 'company', interface: 'input', uiSchema: { type: 'string', title: 'Company', 'x-component': 'Input' } },
    { type: 'string', name: 'title', interface: 'input', uiSchema: { type: 'string', title: 'Job Title', 'x-component': 'Input' } },
    { type: 'string', name: 'email', interface: 'email', uiSchema: { type: 'string', title: 'Email', 'x-component': 'Input' } },
    { type: 'string', name: 'phone', interface: 'phone', uiSchema: { type: 'string', title: 'Phone', 'x-component': 'Input' } },
    { type: 'string', name: 'wechat', interface: 'input', uiSchema: { type: 'string', title: 'WeChat', 'x-component': 'Input' } },
    { type: 'string', name: 'source', interface: 'select', uiSchema: { type: 'string', title: 'Source', 'x-component': 'Select', enum: [{ label: 'Website', value: 'website' }, { label: 'Advertisement', value: 'ad' }, { label: 'Referral', value: 'referral' }, { label: 'Cold Call', value: 'cold_call' }, { label: 'Social Media', value: 'social' }, { label: 'Exhibition', value: 'exhibition' }, { label: 'Partner', value: 'partner' }, { label: 'SEO', value: 'seo' }, { label: 'Content', value: 'content' }, { label: 'Other', value: 'other' }] } },
    { type: 'string', name: 'status', defaultValue: 'new', interface: 'select', uiSchema: { type: 'string', title: 'Status', 'x-component': 'Select', enum: [{ label: 'New', value: 'new' }, { label: 'Contacted', value: 'contacted' }, { label: 'Qualified', value: 'qualified' }, { label: 'Unqualified', value: 'unqualified' }, { label: 'Converted', value: 'converted' }, { label: 'Lost', value: 'lost' }] } },
    { type: 'string', name: 'rating', interface: 'select', uiSchema: { type: 'string', title: 'Rating', 'x-component': 'Select', enum: [{ label: 'Hot', value: 'hot' }, { label: 'Warm', value: 'warm' }, { label: 'Cold', value: 'cold' }] } },
    { type: 'float', name: 'estimatedValue', interface: 'number', uiSchema: { type: 'number', title: 'Estimated Value', 'x-component': 'InputNumber', 'x-component-props': { precision: 2 } } },
    { type: 'string', name: 'industry', interface: 'select', uiSchema: { type: 'string', title: 'Industry', 'x-component': 'Select', enum: [{ label: 'Technology', value: 'tech' }, { label: 'Finance', value: 'finance' }, { label: 'Healthcare', value: 'healthcare' }, { label: 'Manufacturing', value: 'manufacturing' }, { label: 'Retail', value: 'retail' }, { label: 'Education', value: 'education' }, { label: 'Real Estate', value: 'real_estate' }, { label: 'Logistics', value: 'logistics' }, { label: 'Other', value: 'other' }] } },
    { type: 'integer', name: 'employeeCount', interface: 'number', uiSchema: { type: 'number', title: 'Employee Count', 'x-component': 'InputNumber' } },
    { type: 'text', name: 'address', interface: 'textarea', uiSchema: { type: 'string', title: 'Address', 'x-component': 'Input.TextArea' } },
    { type: 'string', name: 'city', interface: 'input', uiSchema: { type: 'string', title: 'City', 'x-component': 'Input' } },
    { type: 'string', name: 'province', interface: 'input', uiSchema: { type: 'string', title: 'Province', 'x-component': 'Input' } },
    { type: 'belongsTo', name: 'owner', target: 'users', foreignKey: 'ownerId', interface: 'm2o', uiSchema: { type: 'object', title: 'Owner', 'x-component': 'AssociationField', 'x-component-props': { fieldNames: { label: 'nickname', value: 'id' } } } },
    { type: 'belongsTo', name: 'campaign', target: 'crmCampaigns', foreignKey: 'campaignId' },
    { type: 'date', name: 'nextFollowUp', interface: 'datetime', uiSchema: { type: 'string', title: 'Next Follow-up', 'x-component': 'DatePicker', 'x-component-props': { showTime: true } } },
    { type: 'date', name: 'convertedAt', interface: 'datetime', uiSchema: { type: 'string', title: 'Converted At', 'x-component': 'DatePicker' } },
    { type: 'belongsTo', name: 'convertedCustomer', target: 'crmCustomers', foreignKey: 'convertedCustomerId' },
    { type: 'text', name: 'notes', interface: 'richText', uiSchema: { type: 'string', title: 'Notes', 'x-component': 'RichText' } },
    { type: 'jsonb', name: 'tags', defaultValue: [] },
  ],
});
